// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg7HFyVCx2Hlox21C9a9WuoC6IU6cKMWw',
    appId: '1:433015377389:web:540e9dabc0fcf35bcb2be4',
    messagingSenderId: '433015377389',
    projectId: 'bayanihan-flutter',
    authDomain: 'bayanihan-flutter.firebaseapp.com',
    databaseURL: 'https://bayanihan-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'bayanihan-flutter.firebasestorage.app',
    measurementId: 'G-FVP6PJY1D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIB1RFup_TA1S8DlshrPZJdgQym0V5j0c',
    appId: '1:433015377389:android:0c1b119d058c89bccb2be4',
    messagingSenderId: '433015377389',
    projectId: 'bayanihan-flutter',
    databaseURL: 'https://bayanihan-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'bayanihan-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKeFoigggV57I6hm7LhtCVWkeC9NL1ITE',
    appId: '1:433015377389:ios:8fb04c111cfc6798cb2be4',
    messagingSenderId: '433015377389',
    projectId: 'bayanihan-flutter',
    databaseURL: 'https://bayanihan-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'bayanihan-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKeFoigggV57I6hm7LhtCVWkeC9NL1ITE',
    appId: '1:433015377389:ios:8fb04c111cfc6798cb2be4',
    messagingSenderId: '433015377389',
    projectId: 'bayanihan-flutter',
    databaseURL: 'https://bayanihan-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'bayanihan-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg7HFyVCx2Hlox21C9a9WuoC6IU6cKMWw',
    appId: '1:433015377389:web:f602d574a2d4e196cb2be4',
    messagingSenderId: '433015377389',
    projectId: 'bayanihan-flutter',
    authDomain: 'bayanihan-flutter.firebaseapp.com',
    databaseURL: 'https://bayanihan-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'bayanihan-flutter.firebasestorage.app',
    measurementId: 'G-23XZW2NB66',
  );

}